# Generated by Django 3.0.3 on 2020-08-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_date',
            field=models.DateField(max_length=64),
        ),
        migrations.AlterField(
            model_name='bid',
            name='starting',
            field=models.BooleanField(max_length=64),
        ),
    ]
