# Generated by Django 3.0.3 on 2020-08-07 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200807_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bid_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
