# Generated by Django 3.0.3 on 2020-08-07 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200807_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_auctionlisting',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, related_name='bid_auctionlisting', to='auctions.AuctionListing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchlist_item',
            field=models.ManyToManyField(blank=True, related_name='watchlist_item', to='auctions.AuctionListing'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchlist_user',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
