# Generated by Django 3.0.3 on 2020-08-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200807_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_auctionlisting',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='comment_auctionlisting', to='auctions.AuctionListing'),
            preserve_default=False,
        ),
    ]
