# Generated by Django 3.0.3 on 2020-08-07 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200807_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watchlist_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
