# Generated by Django 3.0.3 on 2020-08-07 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200807_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='auctionlisting_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctionlisting_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_auctionlisting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_auctionlisting', to='auctions.AuctionListing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_auctionlisting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_auctionlisting', to='auctions.AuctionListing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
