# Generated by Django 3.0.3 on 2020-08-07 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200807_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='auctionlisting_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auctionlisting_category', to='auctions.Category'),
            preserve_default=False,
        ),
    ]
