# Generated by Django 3.0.3 on 2020-08-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200807_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='starting_bid',
        ),
    ]
