# Generated by Django 3.0.3 on 2020-08-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_auctionlisting_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='starting_bid',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
