# Generated by Django 3.0.3 on 2020-08-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auctionlisting_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='bid_is_open',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
