# Generated by Django 3.0.3 on 2020-08-12 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auctionlisting_bid_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='auctionlisting_winning_user',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='auctionlisting_winning_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='winning_bid',
            field=models.FloatField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
