# Generated by Django 3.0.3 on 2020-08-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200812_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='winning_bid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
