# Generated by Django 3.0.3 on 2020-08-12 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200812_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='auctionlisting_winning_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctionlisting_winning_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
