# Generated by Django 3.0.3 on 2020-08-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20200812_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='auctionlisting_winning_user',
            new_name='auctionlisting_winner',
        ),
    ]
