# Generated by Django 3.0.3 on 2020-08-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20200813_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlewatchlist',
            old_name='watchlist_u',
            new_name='watchlist_user',
        ),
    ]
