# Generated by Django 3.0.3 on 2020-08-13 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20200813_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlewatchlist',
            name='watchlist_item',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlist_item', to='auctions.AuctionListing'),
        ),
        migrations.AlterField(
            model_name='singlewatchlist',
            name='watchlist_user',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
