# Generated by Django 3.0.3 on 2020-08-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20200813_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlewatchlist',
            name='active',
        ),
    ]
