# Generated by Django 3.0.3 on 2020-08-13 18:02

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20200813_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(blank=True, default=datetime.now()),
            preserve_default=False,
        ),
    ]
