# Generated by Django 3.0.3 on 2020-08-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20200813_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
