# Generated by Django 2.2.5 on 2020-12-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_auto_20201216_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
