# Generated by Django 2.2.5 on 2020-12-16 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_auto_20201216_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_imgs',
            new_name='image',
        ),
    ]
