version: '3'
services:
  front-app:
    build: .
    container_name: react-app-compose-front
    ports:
      - 3000:3000
    volumes:
      - /Users/ts-fernando.b.takada/Documents/GitHub/cs-50-web-development/project-5-frontapp:/my-app/src