FROM python:3.9.1

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app
COPY . .
RUN pip install -r requirements.txt \
    && python manage.py makemigrations capstone \
    && python manage.py migrate capstone

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]