# Generated by Django 3.0.3 on 2020-09-13 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_post_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_by_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
